webhook:
  host: 0.0.0.0
  port: 11100

memos:
  host: memos
  port: 5230
  token: xxxxxxx

plugins:
  - name: download
    tag: webhook/download
    you_get_plugin:
      patterns:
        - https://twitter.com/\w+/status/\d+
        - https://x.com/\w+/status/\d+
  - name: fix_typos
    tag: task/fix_typos
    zhipu_plugin:
      api_key: xxxxxxx
      prompt: |
        You are a fix typos plugin.
        Please fix the typos in the text.

        The text is:
        ```
        {content}
        ```
  - name: translate
    tag: task/translate
    zhipu_plugin:
      api_key: xxxxxxx
      prompt: |
        You are a translation plugin.
        Please translate the text.

        The text is:
        ```
        {content}
        ```


