version: "3.0"
services:
  memos:
    networks:
      - memos
    image: neosmemo/memos:0.22.1
    container_name: memos
    ports:
      - 5230:5230
  webhook:
    image: ghcr.io/ryojerryyu/memos-webhook-py:test
    networks:
      - memos
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webhook
    environment:
      - LOG_LEVEL=debug
      - MEMOS_HOST=memos
      - MEMOS_PORT=5230
      - MEMOS_TOKEN=xxxxxxxx
    volumes:
      - ./.download:/app/download

networks:
  memos: